### ISSUE TITLE
CSGSI on VB .NET

### ISSUE THREAD

**Issue by spreedated** [rakijah/CSGSI#16]
I'm trying to develop a test application in VB. Problem is, I don't get the event/raiseevent.
In C# it's quit easy with "listener.NewGameState ...", but in VB I don't have the Event.

![image](https://cloud.githubusercontent.com/assets/21370839/25191965/ac7df7a8-2531-11e7-9952-d6d68d5b0227.png)

**Comment by n1lsik** [comment]
https://github.com/rakijah/CSGSI/issues/8
