### ISSUE TITLE
Not working with Danger Zone

### ISSUE THREAD

**Issue by YorVeX** [rakijah/CSGSI#24]
The library is not working properly with Danger Zone, since the GSI got a few new items introduced. To make it work I had to do the following:

- WeaponNode.cs, enum WeaponType: add items "Tablet", "Fists", "BreachCharge" and "Melee"
- MapNode.cs, enum MapMode: add item "Survival" (this is the mode that represents Danger Zone)

**Comment by rakijah** [comment]
Thank you for reporting this. I have just committed/released a new version 34b6cb6b5407386cd42c0c06debbfcaed8a52fb7 that includes these changes (plus a lot of other changes that happened during the past months). NuGet package should be available soon.
