### ISSUE TITLE
Some variables aren't assigned in 1.1.4

### ISSUE THREAD

**Issue by antonpup** [rakijah/CSGSI#4]
I have come across a rather unusual issue. This wasn't occurring before. But some variables never get parsed from the JSON. I have provided an example screenshot. Gamestate says that "Player.Team" is Undefined, while it's base JSON states that player is on T. Same thing goes for the weapons, active weapon isn't initialized, when I have a glock out. Occurs on version 1.1.4
![ver 1.1.4](http://puu.sh/mVFsl/e0d1287bfc.png)

On versions 1.1.2 and 1.1.3 this does not happen.
V1.1.3:
![ver 1.1.3](http://puu.sh/mVG5N/abbfc9f52b.png)
V1.1.2:
![ver 1.1.2](http://puu.sh/mVFVo/f97f40b2f9.png)

**Comment by rakijah** [comment]
Sorry for the inconvenience. It seems I introduced the bug shortly before building the DLL on my local clone of the repository. I was testing with some changes that should not have had an impact on the JSON parsing, but apparently I was wrong.  
These changes never got pushed to the actual repo and I reverted them shortly after building.

I updated the NuGet package with the working version.
