### ISSUE TITLE
Reliable method to determine if map ended

### ISSUE THREAD

**Issue by 2c2c** [rakijah/CSGSI#6]
Does no such thing exist? Determining when game ends and who won has several edge cases that I want to try to avoid dealing with if possible

**Comment by rakijah** [comment]
This isn't exactly an issue related to this specific framework, but I can try to help you anyway.

You can determine when the game has ended by looking at `gameState.Map.Phase`. If it is equal to `MapPhase.GameOver`.

Unfortunately I don't think that Valve has provided a way to actually determine which team won the match. You could try comparing which team won the most rounds, but that may not be accurate in case one team surrendered. You could also try to deduce it from which team that has won the last round (`gameState.Round.WinTeam` when `gameState.Map.Phase == MapPhase.GameOver`).
